# syntax=docker/dockerfile:1
FROM ruby:4.0-slim

# build-essential is needed to compile puma's native extension. It is kept in
# the image (not removed) so the dev compose services can re-run `bundle install`
# against the bind-mounted tree when the Gemfile changes.
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Gems install to the image-global /usr/local/bundle (the base image's GEM_HOME),
# NOT under /app, so the dev `- .:/app` bind mount never shadows them.
# Copy the manifest first for layer caching; the lock is optional on the very
# first build (it is generated by the bootstrap `compose run ... bundle install`).
COPY Gemfile Gemfile.lock* ./
RUN bundle install

# The published image carries the app (incl. the bundled examples/) so it serves
# /templates — or its examples/ fallback — standalone with no bind mount.
COPY . .

EXPOSE 9292

# Boot puma directly so the *published* image runs standalone. The dev compose
# services override this with the scripts/ entrypoints (which bundle install first).
CMD ["sh", "-c", "exec bundle exec puma config.ru -b \"tcp://${BIND:-0.0.0.0}:${PORT:-9292}\""]
